<?php

declare(strict_types=1);

namespace Kachnitel\DynamicFormBundle\Editability;

/**
 * Decides whether a Doctrine entity property should be included in a form
 * generated by DynamicEntityFormType.
 *
 * This is the seam that keeps DynamicEntityFormType and DynamicFormEditabilityListener
 * free of any dependency on a concrete attribute class or expression evaluator.
 * The default binding ({@see AlwaysEditableFieldResolver}) includes every field
 * unconditionally. Consuming applications/bundles override the service alias in
 * their own services.yaml to enforce their own policy — exactly the same pattern
 * kachnitel/entity-components-bundle uses for its own (list-view, inline-edit)
 * EditabilityResolverInterface:
 *
 * ```yaml
 * Kachnitel\DynamicFormBundle\Editability\FieldEditabilityResolverInterface:
 *     alias: App\Form\MyFieldEditabilityResolver
 * ```
 *
 * kachnitel/admin-bundle registers AdminColumnEditabilityResolver, which adds
 * #[AdminColumn(editable: ...)] and #[Admin(enableInlineEdit: ...)] support.
 *
 * ## Why two methods instead of one
 *
 * canEdit() and isExplicitOverride() answer genuinely different questions and
 * must not be collapsed into a single check:
 *
 *   - canEdit() is the general include/exclude gate for an ordinary field. It is
 *     expected to fall back to whatever entity-level default the implementation
 *     defines (e.g. an entity-wide "enable inline edit" flag) when there is no
 *     per-property override.
 *   - isExplicitOverride() is consulted only to decide whether a structurally
 *     auto-skipped association (the inverse side of a bidirectional relationship,
 *     or a ManyToOne back-reference to a parent's collection) should be added back
 *     into the form. It must return true only for an explicit, per-property
 *     opt-in — never by falling back to an entity-level default. An entity with a
 *     permissive entity-level default must not silently pull every auto-skipped
 *     back-reference into the generated form.
 *
 * @see AlwaysEditableFieldResolver
 */
interface FieldEditabilityResolverInterface
{
    /**
     * Whether $property on $entityClass should be included in the generated form.
     *
     * $entity is null when no instance exists yet (building a "new entity" form
     * before anything has been persisted, or before LiveCollectionType has bound
     * a child form to a row). Implementations that need a concrete instance to
     * evaluate a per-row condition should treat null as "cannot resolve yet,
     * default to include" — DynamicFormEditabilityListener re-checks every field
     * once a real (even freshly-`new`'d) entity is bound via PRE_SET_DATA.
     */
    public function canEdit(string $entityClass, string $property, ?object $entity = null): bool;

    /**
     * Whether $property on $entityClass has been explicitly opted back in,
     * overriding DynamicEntityFormType's automatic skipping of inverse-side
     * associations and parent back-references.
     *
     * Must return true only for an explicit per-property override. Unlike
     * canEdit(), this must NOT fall back to any entity-level default.
     */
    public function isExplicitOverride(string $entityClass, string $property, ?object $entity = null): bool;
}
